version: "3.7"
services:
  app:
    image: s00971052s/renting
    ports:
      - 80:3000
    # network_mode: "host"
    working_dir: /usr/app
    environment:
      TOKEN_SECRET: ${TOKEN_SECRET}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}